/* options_cocoa.h: options dialog boxes public declarations
   Copyright (c) 2009 Philip Kendall

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 2 of the License, or
   (at your option) any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License along
   with this program; if not, write to the Free Software Foundation, Inc.,
   51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

   Author contact information:

   E-mail: philip-fuse@shadowmagic.org.uk

*/

/* This file is autogenerated from options.dat by options-cocoa-header.pl.
   Do not edit unless you know what you're doing! */

#ifndef FUSE_OPTIONS_COCOA_H
#define FUSE_OPTIONS_COCOA_H

NSArray * cocoa_sound_stereo_ay( void );

NSArray * cocoa_sound_speaker_type( void );

NSArray * cocoa_diskoptions_drive_plus3a_type( void );

NSArray * cocoa_diskoptions_drive_plus3b_type( void );

NSArray * cocoa_diskoptions_drive_beta128a_type( void );

NSArray * cocoa_diskoptions_drive_beta128b_type( void );

NSArray * cocoa_diskoptions_drive_beta128c_type( void );

NSArray * cocoa_diskoptions_drive_beta128d_type( void );

NSArray * cocoa_diskoptions_drive_plusd1_type( void );

NSArray * cocoa_diskoptions_drive_plusd2_type( void );

NSArray * cocoa_diskoptions_drive_didaktik80a_type( void );

NSArray * cocoa_diskoptions_drive_didaktik80b_type( void );

NSArray * cocoa_diskoptions_drive_disciple1_type( void );

NSArray * cocoa_diskoptions_drive_disciple2_type( void );

NSArray * cocoa_diskoptions_drive_opus1_type( void );

NSArray * cocoa_diskoptions_drive_opus2_type( void );

NSArray * cocoa_diskoptions_disk_try_merge( void );

NSArray * cocoa_movie_movie_compr( void );

#endif				/* #ifndef FUSE_OPTIONS_COCOA_H */
